stages:
  - build
  - validate
  - deploy
  - test
  - staging
  - production
  
build_db:
  image: registry.gitlab.com/dereck.zenda/mysql:latest
  stage: build
  script:

build_app:
  image: registry.gitlab.com/dereck.zenda/wordpress:latest
  stage: build
  script:
    
build_cache:
  image: registry.gitlab.com/dereck.zenda/redis:latest
  stage: build
  script:

testing_app:
  stage: validate
  before_script: []
  script:
    - echo run tests

testing_db:
  stage: validate
  before_script: []
  script:
    - echo run tests

testing_cache:
  stage: validate
  before_script: []
  script:
    - echo run tests


test:
  <<: *deploy
  stage: test
  script:
    - helm install wordpress-app ./templates/values.yml --namespace v1-apps-test

staging:
  <<: *deploy
  stage: test
  script:
    - helm install wordpress-app ./templates/values.yml --namespace v1-apps-uat

production:
  <<: *deploy
  stage: test
  script:
    - helm install wordpress-app ./templates/values.yml --namespace v1-apps-prod